version: '3'
services:
  app:
    build: .
    command: gin --immediate --appPort $PORT
    volumes:
      - .:/bitrise/go/src/github.com/bitrise-team/bitrise-step-analytics
    ports:
      - "3012:3012"
    environment:
      PORT: 3012
      IS_USE_GIN: "yes"