version: '3'
services:
  db:
    image: postgres:10.1
    ports:
      - "5433:5432"
  app:
    build: .
    command: gin --immediate --appPort $PORT
    volumes:
      - .:/bitrise/go/src/github.com/bitrise-team/bitrise-step-analytics
    ports:
      - "3011:3001"
    links:
      - db:postgres
    environment:
      PORT: 3011
      IS_USE_GIN: "yes"